app/home/forms.py
#!/usr/bin/env python
# _*_ coding:utf-8 _*_
# Author:Arthur

from flask_wtf import FlaskForm
from flask import session
from wtforms import StringField, PasswordField, SubmitField,TextAreaField
from wtforms.validators import DataRequired, EqualTo, Email, Length, ValidationError
from flask_wtf.file import FileField,FileAllowed
from app.models import User


class LoginForm(FlaskForm):
    """
    登录表单
    """
    username = StringField('账号', validators=[DataRequired("用户名不能为空"),
                                             Length(2, 20, message="用户名长度为2-20位"),

                                             ])

    password = PasswordField('密码', validators=[DataRequired("密码不能为空"),
                                               Length(6, 18, message="密码长度为6-18为")])

    submit = SubmitField()

    def validate_username(self, field):
        user = User.query.filter_by(username=field.data).first()
        if not user:
            raise ValidationError("用户名不存在")


class RegisterForm(FlaskForm):
    """
    注册表单
    """
    username = StringField('用户名', validators=[DataRequired("用户名不能为空"),
                                              Length(2, 20, message="用户名长度为2-20位"),

                                              ])
    email = StringField('邮箱', validators=[DataRequired("邮箱不能为空"), Email("邮箱格式不正确")])
    password = PasswordField('密码', validators=[DataRequired("密码不能为空"),
                                               Length(6, 18, message="密码长度为6-18为")])
    password2 = PasswordField('密码', validators=[EqualTo('password', message="两次输入的密码不一致")])

    phone_num = StringField("手机", validators=[Length(11, 11, message="手机号码需11位数字")])
    submit = SubmitField('登录')

    def validate_username(self, flied):
        user = User.query.filter_by(username=flied.data).count()
        if user != 0:
            raise ValidationError("用户名已存在")

    def validate_email(self, flied):
        email = User.query.filter_by(email=flied.data).count()
        if email != 0:
            raise ValidationError("邮箱已存在已存在")

    def validate_phone_num(self, flied):
        phone_num = User.query.filter_by(phone_num=flied.data).count()
        if phone_num != 0:
            raise ValidationError("号码已存在")

class UserForm(FlaskForm):
    """
    会员表单
    """
    username = StringField("用户",validators=[DataRequired("用户不能为空")])
    email = StringField("邮箱",validators=[Email("邮箱格式不正确")])
    phone_num = StringField("手机",validators=[Length(11,11,message="号码长度为11位")])
    avatar = FileField("头像",validators=[FileAllowed(['jpg','jpeg','png'],message="该格式不支持")])
    info = TextAreaField("简介")
    submit = SubmitField()

class PwdForm(FlaskForm):
    """
    修改密码表单
    """
    old_pwd = PasswordField('旧密码', validators=[DataRequired("密码不能为空"),
                                               Length(6, 18, message="密码长度为6-18为")])
    pwd = PasswordField('新密码', validators=[DataRequired("密码不能为空"),
                                               Length(6, 18, message="密码长度为6-18为")])
    pwd2 = PasswordField('重复密码', validators=[EqualTo('pwd',message="两次输入的密码不一致")])

    submit = SubmitField()

    def validate_old_pwd(self,field):
        user = User.query.filter_by(username=session.get('user')).first()
        if not user.check_password(field.data):
            raise ValidationError("原密码有误")



class CommentForm(FlaskForm):
    """
    评论表单
    """
    content = TextAreaField("内容", validators=[DataRequired("评论不能为空")])
    submit = SubmitField()

app/home/__init__.py
#!/usr/bin/env python
# _*_ coding:utf-8 _*_
# Author:Arthur

"""
前台模块
"""

from flask import Blueprint

home = Blueprint('home', __name__)



from app.home import forms, views

app/home/views.py
#!/usr/bin/env python
# _*_ coding:utf-8 _*_
# Author:Arthur

import os
from flask import render_template, redirect, flash, request, url_for, session, Response
from uuid import uuid4
from datetime import datetime
import json
from werkzeug.utils import secure_filename
from tools import change_upload_filename
from app import app, db, rd
from app.home import home
from .forms import LoginForm, RegisterForm, UserForm, PwdForm, CommentForm
from app.models import User, UserLog, Preview, Tag, Movie, Comment, Moviecol
from tools import user_login_req


# 主页
@home.route('/', methods=["GET"])
def index():
    tags = Tag.query.all()
    page_data = Movie.query

    # 标签
    tid = request.args.get('tid', 0)
    if int(tid) != 0:
        page_data = page_data.filter_by(tag_id=int(tid))
    # 星级
    star = request.args.get('star', 0)
    if int(star) != 0:
        page_data = page_data.filter_by(star=int(star))
    # 上映时间
    time = request.args.get('time', 0)
    if int(time) != 0:
        if int(time) == 1:
            page_data = page_data.order_by(Movie.addtime.desc())
        else:
            page_data = page_data.order_by(Movie.addtime.asc())
    # 播放量
    pm = request.args.get('pm', 0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(Movie.playnum.desc())
        else:
            page_data = page_data.order_by(Movie.playnum.asc())
    # 评论量
    cm = request.args.get('cm', 0)
    if int(cm) != 0:
        if int(cm) == 1:
            page_data = page_data.order_by(Movie.commentnum.desc())
        else:
            page_data = page_data.order_by(Movie.commentnum.asc())

    page = int(request.args.get('page', 1))
    page_data = page_data.paginate(page, 10)
    p = {
        "tid": tid,
        "star": star,
        "time": time,
        "cm": cm,
        "pm": pm,
        "page": page,

    }

    return render_template('home/index.html', tags=tags, p=p, page_data=page_data)


# 评论
@home.route('/search')
@home.route('/search/<int:page>', methods=['get', 'post'])
def search(page=None):
    if page is None:
        page = 1
    key = request.args.get('key')
    if not key:
        key = request.form.get('key')
    page_data = Movie.query
    page_data = page_data.filter(Movie.title.ilike("%" + key + "%"))
    page_data = page_data.filter(Movie.info.ilike("%" + key + "%")).paginate(page, 10)
    return render_template('home/search.html', key=key, page_data=page_data)


# 评论
@home.route('/comments')
@home.route('/comments/<int:page>')
@user_login_req
def comments(page=None):
    if page == None:
        page = 1
    user = User.query.filter_by(username=session.get('user')).first()
    page_data = Comment.query.filter_by(user_id=user.id).paginate(page, 10)

    return render_template('home/comments.html', user=user, page_data=page_data)


# 登录日志
@home.route('/loginlog')
@home.route('/loginlog/<int:page>')
def loginlog(page=None):
    if page is None:
        page = 1
    page_data = UserLog.query.filter_by(user_id=int(session.get('User_id'))).order_by(UserLog.addtime).paginate(page,
                                                                                                                10)

    return render_template('home/loginlog.html', page_data=page_data)


# 添加电影收藏
@home.route('/moviecol/add')
def moviecol_add():
    uid = int(request.args.get('uid', ""))
    mid = int(request.args.get("mid", ""))
    moviecol = Moviecol.query.filter_by(
        user_id=int(uid),
        movie_id=int(mid)
    ).count()
    if moviecol == 0:
        m = Moviecol(user_id=uid, movie_id=mid)
        db.session.add(m)
        db.session.commit()
        data = dict(ok=1)
    else:
        data = dict(ok=0)
    return json.dumps(data)


# 收藏电影
@home.route('/moviecol')
@home.route('/moviecol/<int:page>')
def moviecol(page=None):
    if page is None:
        page = 1
    page_data = Moviecol.query.filter_by(user_id=int(session.get('User_id'))).join(Movie).join(User).filter(
        Moviecol.movie_id == Movie.id,
        Moviecol.user_id == User.id
    ).order_by(Moviecol.addtime.desc()).paginate(page, 10)

    return render_template('home/moviecol.html', page_data=page_data)


# 播放页
@home.route('/play/<int:id>', methods=["GET", "POST"])
@home.route('/play/<int:id>/<int:page>', methods=["GET", "POST"])
def play(id=None, page=None):
    if page == None:
        page = 1
    movie = Movie.query.get_or_404(id)
    movie.playnum += 1
    form = CommentForm()
    # 评论
    if session.get('user') and form.validate_on_submit():
        data = form.data
        comm = Comment(content=data['content'],
                       user_id=session.get('User_id'),
                       movie_id=movie.id)
        db.session.add(comm)
        db.session.commit()
        movie.commentnum += 1
        db.session.add(movie)
        db.session.commit()
        flash("评论成功", "ok")
        return redirect(url_for('home.play', id=movie.id))
    db.session.add(movie)
    db.session.commit()
    # 评论列表

    page_data = Comment.query.join(User).filter(User.id == Comment.user_id).order_by(Comment.addtime.desc()).paginate(
        page, 10)
    return render_template('home/play.html', movie=movie, form=form, page_data=page_data, page=page)


# 播放页
@home.route('/vedio/<int:id>', methods=["GET", "POST"])
@home.route('/vedio/<int:id>/<int:page>', methods=["GET", "POST"])
def vedio(id=None, page=None):
    if page == None:
        page = 1
    movie = Movie.query.get_or_404(id)
    movie.playnum += 1
    form = CommentForm()
    # 评论
    if session.get('user') and form.validate_on_submit():
        data = form.data
        comm = Comment(content=data['content'],
                       user_id=session.get('User_id'),
                       movie_id=movie.id)
        db.session.add(comm)
        db.session.commit()
        movie.commentnum += 1
        db.session.add(movie)
        db.session.commit()
        flash("评论成功", "ok")
        return redirect(url_for('home.vedio', id=movie.id))
    db.session.add(movie)
    db.session.commit()
    # 评论列表

    page_data = Comment.query.join(User).filter(User.id == Comment.user_id).order_by(Comment.addtime.desc()).paginate(
        page, 10)
    return render_template('home/vedio.html', movie=movie, form=form, page_data=page_data, page=page)


@app.route('/danmu', methods=['get', 'post'])
def danmu():
    if request.method == "GET":
        id = request.args.get('id')
        key = 'movie' + str(id)
        if rd.llen(key):
            msgs = rd.lrange(key, 0, 2999)
            res = {
                'code': 1,
                'danmaku': [json.loads(v) for v in msgs]
            }
        else:
            res = {
                'code': 1,
                'danmuku': []
            }
        resp = json.dumps(res)
    if request.method == "POST":
        data = json.loads(request.get_data())
        msg = {
            "__v": 0,
            "author": data["author"],
            "time": data["time"],
            "text": data["text"],
            "color": data["color"],
            "type": data['type'],
            "ip": request.remote_addr,
            "_id": datetime.now().strftime("%Y%m%d%H%M%S") + uuid4().hex,
            "player": [data["player"]]

        }
        res = {
            'code': 1,
            'data': msg
        }
        resp = json.dumps(res)
        rd.lpush('movie' + str(data['player']), json.dumps(msg))
    return Response(resp, mimetype='application/json')


# 登录
@home.route('/login', methods=['get', 'post'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        print("用户名：{}".format(user.username))
        print("传入的密码:{}".format(form.password.data))
        if user and user.check_password(form.password.data):
            session['user'] = user.username
            session['User_id'] = user.id
            # 持久化　默认保存31天，可通过在config中设置PERMENENT_SESSION_LIFETIME改变
            session.permanent = True
            userlog = UserLog(
                ip=request.remote_addr,
                user_id=user.id,
            )
            db.session.add(userlog)
            db.session.commit()

            return redirect(url_for('home.index'))
        else:
            flash("密码错误", "err")
    return render_template('home/login.html', form=form)


# 注册
@home.route('/register', methods=['get', 'post'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(
            username=data['username'],
            email=data['email'],
            phone_num=data['phone_num'],
            password=data['password'],
            avatar="link111.jpg",
            uuid=uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash("注册成功", 'ok')
        return redirect(url_for('home.login'))

    return render_template('home/register.html', form=form)


# 退出
@home.route('/logout')
def logout():
    # 删除session
    session.clear()
    return redirect(url_for('home.login'))


# 会员
@home.route('/user', methods=['get', 'post'])
@user_login_req
def user():
    form = UserForm()
    user = User.query.get_or_404(session.get('User_id'))
    if request.method == 'GET':
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data
        if user.username != data['username']:
            c = User.query.filter_by(username=data['username']).count()
            if c != 0:
                flash("用户名已存在", "err")
                return redirect(url_for('home.user'))
            user.username = data['username']
        if user.email != data['email']:
            c = User.query.filter_by(email=data['email']).count()
            if c != 0:
                flash("邮箱已存在", "err")
                return redirect(url_for('home.user'))
            user.email = data['email']
        if user.phone_num != data['phone_num']:
            c = User.query.filter_by(phone_num=data['phone_num']).count()

app/templates/home/animation.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>热映电影</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='animation/css/style.css') }}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
	<div class="main_banner_wrap">
		<canvas id="myCanvas" width="150" height="150"></canvas>
		<div class="main_banner_box" id="m_box">
			<a href="javascript:void(0)" class="banner_btn js_pre">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<a href="javascript:void(0)" class="banner_btn btn_next js_next">
				<span class="banner_btn_arrow"><i></i></span>
			</a>
			<ul>
                {% for v in preview %}
				<li id="imgCard{{loop.index0}}">

					<a href=""><span style="opacity:0;"></span></a>      
					<img src="{{ url_for('static',filename='uploads/pic/'+v.logo) }}" alt="">
					<p style="bottom:0">{{ v.title }}</p>
				</li>
                {% endfor %}

			</ul>
			<!--火狐倒影图层-->
			<p id="rflt"></p>
			<!--火狐倒影图层-->
		</div>
		<!--序列号按钮-->
		<div class="btn_list">
			<span class="curr"></span><span></span><span></span><span></span><span></span>        
		</div>
	</div>
	
</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{ url_for('static',filename='animation/js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static',filename='animation/js/script.js') }}"></script>

</body>
</html>

app/templates/home/comments.html
{% extends "home/user_base.html" %}
{% import "ui/home_page.html" as pg %}
{% block user %}
     <div class="col-md-9">
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;评论记录</h3>
            </div>
            <div class="panel-body">
                <ul class="commentList">
                {% for v in page_data.items %}
                        <li class="item cl">
                            <a href="user.html">
                                <i class="avatar size-L radius">
                                    {% if user.avatar %}
                                         <img alt="50x50" src="{{ url_for('static',filename='uploads/avatar/'+user.avatar) }}" class="img-circle" style="border:1px solid #abcdef; width: 50px; height: 50px;">
                                    {% else %}
                                        <img alt="50x50" src="{{ url_for('static',filename='uploads/avatar/link111.jpg') }}" class="img-circle" style="border:1px solid #abcdef; width: 50px; height: 50px;">
                                    {% endif %}

                                </i>
                            </a>
                            <div class="comment-main">
                                <header class="comment-header">
                                    <div class="comment-meta">
                                        <a class="comment-author" href="">{{ user.username }}</a>
                                        评论于
                                        <time title="{{ v.addtime }}" datetime="{{ v.addtime }}">{{ v.addtime }}</time>
                                    </div>
                                </header>
                                <div class="comment-body">
                                    <p>{{ v.content|safe}}</p>
                                </div>
                            </div>
                        </li>
                {% endfor %}

                    </ul>
                    <div class="col-md-12 text-center">
                        <nav aria-label="Page navigation">
                           {{ pg.page(page_data,'home.comments') }}
                        </nav>
                    </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/home/index.html
{% extends "home/nav.html" %}
{% block content %}
<!--内容-->
<!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            {% for v in tags %}
                            <a href="{{ url_for('home.index') }}?tid={{ v.id }}&star={{ p['star'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}&time={{ p['time'] }}&page={{ p['page'] }}" class="label label-info"><span class="glyphicon glyphicon-tag"></span>{{ v.name }}</a>
                            {% endfor %}
                            &nbsp;
                     </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            {% for n in range(1,6) %}
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ n }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}&time={{ p['time'] }}&page={{ p['page'] }}" class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;{{ n|star }}星</a>
                            {% endfor %}
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}&time=1&page={{ p['page'] }}" class="label label-default"><span class="glyphicon glyphicon-time">&nbsp;最近</span></a>

                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}&time=2&page={{ p['page'] }}" class="label label-default"><span class="glyphicon glyphicon-time">&nbsp;更早</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&pm=1&cm={{ p['cm'] }}&time={{ p['time'] }}&page={{ p['page'] }}" class="label label-success"><span class="glyphicon glyphicon-arrow-down">从高到底</span></a>
                            &nbsp;
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&pm=2&cm={{ p['cm'] }}&time={{ p['time'] }}&page={{ p['page'] }}" class="label label-danger"><span class="glyphicon glyphicon-arrow-up">从低到高</span></a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&pm={{ p['pm'] }}&cm=1&time={{ p['time'] }}&page={{ p['page'] }}" class="label label-success"><span class="glyphicon glyphicon-arrow-down">&nbsp;从高到底</span></a>
                            &nbsp;
                            <a href="{{ url_for('home.index') }}?tid={{ p['tid'] }}&star={{ p['star'] }}&pm={{ p['pm'] }}&cm=2&time={{ p['time'] }}&page={{ p['page'] }}" class="label label-danger"><span class="glyphicon glyphicon-arrow-up">从低到高</span></a>
                        </td>
                    </tr>
                </table>
            </div>
            {% for v in page_data.items %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="{{ url_for('static',filename='uploads/pic/'+v.logo) }}" style="width: 262px; height: 166px;" class="img-responsive center-block">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">{{ v.title }}</span><br>
                        <div>
                            {% for n in range(v.star) %}
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                {% endfor %}
                            {% for n in range(5-v.star) %}
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>

                                {% endfor %}
                        </div>
                    </div>
                    <a href="{{url_for('home.play',id=v.id)}}" class="btn btn-primary" target="_blank" role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}

            <div class="col-md-12">
                <nav aria-label="Page navigation">
             <ul class="pagination">
        <li>
            <a href="{{ url_for('home.index',page=1) }}" aria-label="First">
                <span aria-hidden="true">首页</span>
            </a>
        </li>
        {% if page_data.has_prev %}
            <li>
                <a href="{{ url_for('home.index',page=page_data.prev_num) }}" aria-label="Previous">
                    <span aria-hidden="true">上一页</span>
                </a>
            </li>
            {% else %}
                   <li class="disabled" >
                        <a aria-label="Previous">
                            <span aria-hidden="true">上一页</span>
                        </a>
                     </li>
        {% endif %}
        <li><a>{{ page_data.page }}/&nbsp;{{ page_data.pages }}</a></li>
        {% if page_data.has_next %}
            <li>
                <a href="{{ url_for('home.index',page=page_data.next_num) }}" aria-label="Previous">
                    <span aria-hidden="true">下一页</span>
                </a>
            </li>
            {% else %}
                   <li class="disabled" >
                        <a aria-label="Previous">
                            <span aria-hidden="true">下一页</span>
                        </a>
                     </li>
        {% endif %}

        <li>
            <a href="{{ url_for('home.index',page=page_data.pages) }}" aria-label="Last">
                <span aria-hidden="true">尾页</span>
            </a>
        </li>
    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->
{% endblock %}

app/templates/home/nav.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='base/images/logo.png')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/bootstrap-movie.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='base/css/animate.css')}}">
   {% block head %}{% endblock %}
    <style>
        .navbar-brand>img {
            display: inline;
        }

    </style>
    <style>
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index') }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <div class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    {% if not key %}
                        <input id="key_movie" type="text" class="form-control" placeholder="请输入电影名！">
                    {% else %}
                    <input id="key_movie" type="text" class="form-control" value="{{ key }}">
                    {% endif %}
                    <span class="input-group-btn">
                        <a id="do_search" class="btn btn-default"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>


                 {%  if session['user'] %}
                 <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                {% else %}
                        <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                {% endif %}

            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}{% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js')}}"></script>
<script src="{{ url_for('static',filename='base/js/wow.min.js')}}"></script>
<script src="{{ url_for('static',filename='lazyload/jquery.lazyload.min.js')}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
{% block footer %}{% endblock %}
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#do_search").click(function () {
            var key = $("#key_movie").val();
            location.href = "{{ url_for('home.search') }}?key="+key;

        });
        $("#key_movie").keydown(function (e) {
            if (e.keyCode == 13){
                var key = $("#key_movie").val();
                location.href = "{{ url_for('home.search') }}?key="+key;

            }

        });
    });

</script>
</body>
</html>

app/templates/home/user_base.html
{% extends "home/nav.html" %}
    {% block content %}
    <div class="col-md-3">
        <div class="list-group">
            <a href="{{ url_for('home.user') }}" class="list-group-item active">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
             <a href="{{ url_for('home.pwd') }}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a href="{{ url_for('home.comments') }}" class="list-group-item">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a href="{{ url_for('home.loginlog',page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a href="{{ url_for('home.moviecol') }}" class="list-group-item">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
            </a>
        </div>
    </div>
        {% block user %}{% endblock %}

{% endblock %}